### ISSUE TITLE
Error is occurred when I run main.py

### ISSUE THREAD

**Issue by Shiva-KT** [cly1994jlu/UARA-DRL#2]
Hello,
I run main.py but I get following error:
sce = DotDic(json.loads(open(args.config_path1, 'r').read()))
TypeError: expected str, bytes or os.PathLike object, not NoneType

Could you please help me with why this error occurs?

**Comment by salari90** [comment]
i have the same problem.
did you solve it?

**Comment by salari90** [comment]
> Hello, I run main.py but I get following error: sce = DotDic(json.loads(open(args.config_path1, 'r').read())) TypeError: expected str, bytes or os.PathLike object, not NoneType
> 
> Could you please help me with why this error occurs?

I'll be thanx if you help me

**Comment by zly336** [comment]
> [salari90](/salari90)

你好，我也遇到了相同的问题，请问你解决了么，如果你能帮助我i，我非常感谢

**Comment by zly336** [comment]
Hello, I encountered the same problem. Have you solved it? I would be very grateful if you could help me.
